// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"astralink/internal/db"
	"astralink/internal/repo"
	"astralink/internal/service"
)

// Injectors from wire.go:

// InitializeApp 依赖注入入口
func InitializeApp(basePath string) (*App, error) {
	gormDB, err := db.InitDB(basePath)
	if err != nil {
		return nil, err
	}
	index, err := db.BleveInit(basePath)
	if err != nil {
		return nil, err
	}
	baseRepo := repo.NewBaseRepo(gormDB, basePath, index)
	nodeService := service.NewNodeService(baseRepo)
	relationService := service.NewRelationService(baseRepo)
	app := NewApp(baseRepo, nodeService, relationService)
	return app, nil
}
