// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"astralink/internal/db"
	"astralink/internal/repo"
	"astralink/internal/service"
)

func InitializeApp(basePath string) (*App, error) {
	gormDB, err := db.InitDB(basePath)
	if err != nil {
		return nil, err
	}
	baseRepo := repo.NewBaseRepo(gormDB, basePath)
	nodeService := service.NewNodeService(baseRepo)
	app := NewApp(baseRepo, nodeService)
	return app, nil
}
